ctl_button.o: ctl_button.c dialogs.h ctl_button.h
ctl_checkbox.o: ctl_checkbox.c dialogs.h ctl_checkbox.h
ctl_edit.o: ctl_edit.c unicode.h dialogs.h ctl_edit.h
ctl_groupbox.o: ctl_groupbox.c dialogs.h ctl_groupbox.h
ctl_hotkey.o: ctl_hotkey.c dialogs.h ctl_hotkey.h
ctl_image.o: ctl_image.c dialogs.h ctl_image.h
ctl_label.o: ctl_label.c dialogs.h ctl_label.h
ctl_listview.o: ctl_listview.c unicode.h dialogs.h ctl_listview.h
ctl_progress.o: ctl_progress.c unicode.h dialogs.h ctl_progress.h
ctl_richview.o: ctl_richview.c unicode.h dialogs.h ctl_richview.h
dialogs.o: dialogs.c unicode.h dialogs.h
dlgpack.o: dlgpack.c unicode.h dialogs.h
unicode.o: unicode.c unicode.h
